# Copy the config file, restart the service
---
- name: Configure Logstash
  ansible.builtin.template:
    src: ../files/{{ item.name }}
    dest: /etc/logstash/conf.d/{{ item.name }}
    loop: "{{ logstash_pipelines }}"

# - name: copy input, output and filter files
#   ansible.builtin.template:
#     src: '{{ item }}.conf.j2'
#     dest: '/etc/logstash/conf.d/{{ item }}.conf'
#     owner: root
#     group: root
#     mode: 0644
#     validate: /usr/share/logstash/bin/logstash -t -f %s
#   loop:
#     - input
#     - output
#     - filter
#   notify: restart logstash
#   tags: logstash

# - name: copy multiple items
#     copy: 
#       src: "{{ item.src }}" 
#       dest: "{{ item.dest }}"
#     loop:
#       - src: containerizers
#         dest: /etc/mesos/containerizers
#       - src: another_file
#         dest: /etc/somewhere
#       - src: dynamic
#         dest: "{{ var_path }}"

- name: Restart Logstash
  ansible.builtin.service:
    name: "logstash.service"
    state: restarted
