# Copy the config file, restart the service
---
# - name: Print some message (loop test)
#   ansible.builtin.debug:
#     msg: This is a {{ item }} message
  # loop:
  #   - first
  #   - second
  #   - third

- name: Configure Logstash
  ansible.builtin.template:
    src: ../files/{{ item }}
    dest: /etc/logstash/conf.d/{{ item }}
  loop: "{{ logstash_pipelines }}"

- name: Restart Logstash
  ansible.builtin.service:
    name: "logstash.service"
    state: restarted
