# Copy the config file
---
- name: Configure Nginx
  template:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf

# - name: Reload nginx
#   ansible.builtin.service:
#     name: "nginx.service"
#     state: reloaded

- name: Restart nginx
  ansible.builtin.service:
    name: "nginx.service"
    state: restarted
