name: Deploy with Ansible

on:
  push:
    branches:
      # - 'main'
      - 'dev'

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: self-hosted
    # environment: development
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'SSH test'
        shell: bash
        run: |
          ip addr

      # To elevate privileges, use either: sudoers or sudo -S
      - name: 'Install Ansible'
        shell: bash
        run: |
          echo ${{ secrets.PASSWORD }} | sudo -S apt update
          echo ${{ secrets.PASSWORD }} | sudo -S apt install -y ansible

      - name: 'Ansible version'
        shell: bash
        run: |
          ansible --version

      - name: 'Run Ansible Playbook'
      #   env:
      #     ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      #     ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook playbook_hello_world.yaml