name: Deploy with Ansible

on:
  push:
    branches:
      # - 'main'
      - 'dev'
    # paths:
    #   - 'playbooks/**'

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: self-hosted
    # environment: development
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: 'SSH test'
        shell: bash
        run: |
          ip addr

      # - name: 'Set up SSH'
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
      #     chmod 600 private_key.pem

      # sudoers
      - name: 'Install Ansible'
        shell: bash
        run: |
          pip install ansible
          # sudo apt update
          # sudo apt install -y ansible

      # - name: 'Run Ansible Playbook'
      #   env:
      #     ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      #     ANSIBLE_HOST_KEY_CHECKING: False
      #   run: |
      #     ansible-playbook -i inventory/hosts.ini playbooks/deploy_web_server.yml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }}