name: Deploy with Ansible prod

on:
  push:
    branches:
      - 'main'
    #   - 'dev'

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: self-hosted
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      - name: Main branch - Prod info
        run: |
          echo 'Lack of resources to create NGINX PROD environment...'
