name: Deploy with Ansible dev

on:
  push:
    branches:
      # - 'main'
      - 'dev'

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: self-hosted
    # environment: development
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5

      # - name: 'SSH test'
      #   shell: bash
      #   run: |
      #     ip addr

      # To elevate privileges, use either: sudoers or sudo -S
      - name: 'Install Ansible'
        shell: bash
        run: |
          echo ${{ secrets.PASSWORD }} | sudo -S apt update
          echo ${{ secrets.PASSWORD }} | sudo -S apt install -y ansible

      - name: 'Ansible version'
        shell: bash
        run: |
          ansible --version

      - name: 'Run Nginx Ansible Playbook'
      # Install sshpass on runner for Ansible SSH connection
        run: |
          ansible-playbook playbook_rev_nginx.yaml --extra-vars "ansible_sudo_pass=${{ secrets.PASSWORD }} ansible_user=${{ secrets.USERNAME }} ansible_ssh_pass=${{ secrets.PASSWORD }}"

      - name: 'Run Logstash Ansible Playbook'
        run: |
          ansible-playbook playbook_logstash.yaml --extra-vars "ansible_sudo_pass=${{ secrets.PASSWORD }} ansible_user=${{ secrets.USERNAME }} ansible_ssh_pass=${{ secrets.PASSWORD }}"